services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile-mariadb
    image: mariadb:noble-madrid
    container_name: PHPForm-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: abc123.
      MYSQL_DATABASE: PHPFormBD
      MYSQL_USER: admin
      MYSQL_PASSWORD: abc123.
    ports:
      - "8806:3306"
    networks:
      phpform-net:
        ipv4_address: 172.20.0.2

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile-apache
    image: php:apache-bullseye-pdo
    container_name: PHPForm-apache
    ports:
      - "8888:80"
    volumes:
      - ./html:/var/www/html
    networks:
      phpform-net:
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin:apache
    container_name: PHPForm-pma
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: abc123.
    networks:
      phpform-net:
    ports:
      - "8889:80"
    depends_on:
      - mariadb

networks:
  phpform-net:
    name: phpform-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
